import com.example.html.* // see declarations below
import de.hshl.isd.ui.*

val poem = "poem"
fun buildView() =
    view("Main") {
        dependencies {
            dependency<RequestVerses>("poetryReader")
        }
        state<String>(poem)
        vstack(
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.SpaceAround
        ) {
            text("Poetry Reader", font = Font.Title)
            button(action = tapAction()) {
                text("Give me some poetry")
            }
            text(poem)
        }
    }

fun tapAction(): () -> Unit {
    return {}
}

fun result(args: Array<String>) =
    html {
        head {
            title {+"XML encoding with Kotlin"}
        }
        body {
            h1 {+"XML encoding with Kotlin"}
            p  {+"this format can be used as an alternative markup to XML"}

            // an element with attributes and text content
            a(href = "https://kotlinlang.org") {+"Kotlin"}

            // mixed content
            p {
                +"This is some"
                b {+"mixed"}
                +"text. For more see the"
                a(href = "https://kotlinlang.org") {+"Kotlin"}
                +"project"
            }
            p {+"some text"}

            // content generated by
            p {
                for (arg in args)
                    +arg
            }
        }
    }

val destination = Destination.SwiftUI
fun main(args: Array<String>) {
    println(buildView())
    //println(result(args))
}